mindmap
  root))Judo((
    ((Werfen))
      o-Goshi
      Tomonage
      O-uschi-Gari
      Fußfeger
    ((Haltegriffe))
      Yoko-scchio-gatame
      kami-schio-gatame
      mune-gatame
      Kesa-gatame
      Tate-schio-gatame
    )Freunde(
      Sara
      Johanna
      Xenio
      Jojo
      Sofie
    Judowerte
      Respekt
      Hilfsbereitschaft
      Ernsthaftigkeit
      Freundschaft
      Mut
      Bescheidenheit
     Selbstbeherschung
     Wertschätzung
     Höfichkeit
    [Dojo]
      Übungshalle
    (Tatami)
     Judomatten
    (Kimono)
       Judoanzug
       ((Judogürtel))
         1.Weiß-Gelb
         2.Gelb
         3.Gelb-Orange
         4.Orange
         5.orange-Grün
         6.Grün
         7.Blau
         8.Braun
