mindmap
  root((Judo))
    ))Werfen((
      o-Goshi
      Tomonage
      O-uschi-Gari
      Fußfeger
    )Haltegriffe(
      Kesa-gatame
      Tate-schio-gatame
    (Freunde)
      Sara
      Johanna
      Xenio
      Jojo
      Sofie
    [Judowerte]
      Respekt
      Hilfsbereitschaft
      Ernsthaftigkeit
      Freundschaft
      Mut
      Bescheidenheit
     Selbstbeherschung
     Wertschätzung
     Höfichkeit
    {{Dojo}}
      Übungshalle
    {{Tatami}}
      Matten
    {{Kimono}}
       Judoanzug
       Gürtel
